### PR TITLE
PlanSys2 info added

### PR DESCRIPTION
**Pull request by fmrico**
Hi!!

This PR adds info about [ROS2 Planning System](https://github.com/IntelligentRoboticsLabs/ros2_planning_system).

I hope it will be interesting for the planning community :)

Best
Francisco

Signed-off-by: Francisco Martin Rico <fmrico@gmail.com>

### CODE REVIEW

**Comment by fmrico** [comment]
Hi @nergmada 

I am not really sure if the errors in CI is because of my PR. It seems to be an internal error :+1: 

```
1:35:27 PM:   Liquid Exception: Liquid error (/opt/build/cache/bundle/ruby/2.6.0/gems/just-the-docs-0.3.1/_includes/nav.html line 9): comparison of Array with Array failed included in /_layouts/default.html
1:35:27 PM: jekyll 3.8.7 | Error:  Liquid error (/opt/build/cache/bundle/ruby/2.6.0/gems/just-the-docs-0.3.1/_includes/nav.html line 9): comparison of Array with Array failed included
```

**Comment by nergmada** [comment]
No worries, I'll take a look at the CI. It's been a long time since I set up the CI, it's probably in need of a kickstart

**Comment by nergmada** [comment]
Hi @fmrico I have found the issue. It's not your fault, what's happened is related to how the theme we use for the planning wiki sorts pages. It's a big ask, but would you be able to open the file `404.md` on your branch, and change
`title: 404` to `title: "404"`. I.e. add quote marks around the 404. This should fix the build issue and when merged prevent the issue from happening again

**Comment by fmrico** [comment]
Hi @nergmada 

It seems like that fixed the problem :)

Best

**Pull request merged**
